version: "3.9"

services:
    server:
        container_name: prakticum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        env_file: 
          - .env
        depends_on:
          - postgres
        networks:
          - prakticum

    pgadmin:
      container_name: prakticum-pgadmin
      image: dpage/pgadmin4:4.18
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
        PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
        PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
      env_file: 
        - .env
      ports:
        - "${PGADMIN_HOST_PORT}:${PGADMIN_LISTEN_PORT}"
      volumes:
        - ./tmp/pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - prakticum

    postgres:
      container_name: prakticum-postgres
      image: postgres:14     
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      volumes:
        - ./tmp/pg-data:/var/lib/postgresql/data
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      env_file: 
        - .env
      networks:
        - prakticum

volumes:
  pgadmin-data:

networks:
  prakticum:
    driver: bridge
