export const BACKGROUND = '#1e1e1e'
export const DEEP_PINK = '#ff4d8d'
export const LIGHT_PINK = '#ff87b2'
export const RED_TEXT = '#ff8c69'
export const WHITE_TEXT = '#f7f7f7'
export const LIGHT_GREY = '#8e8e8e'

export const DEEP_GREEN = '#3BA185'
export const DEEP_OCEAN = '#00536B'
export const LIGHT_OCEAN = '#D3F5FF'
export const COLD_GREY = '#262626'
