export const BACKGROUND = '#222222'
export const DEEP_PINK = '#ff4d8d'
export const LIGHT_PINK = '#ff87b2'
export const RED_TEXT = '#ff8c69'
export const WHITE_TEXT = '#f7f7f7'
export const LIGHT_GREY = '#adadad'
export const ORANGE = '#EDB660'

export const DEEP_GREEN = '#3BA185'
export const DEEP_OCEAN = '#00536B'
export const LIGHT_OCEAN = '#D3F5FF'
export const DEEP_PURPLE = '#62259F'
export const COLD_GREY = '#404040'
